# Generated by Django 5.2 on 2025-05-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_contactinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="categories/%Y/%m/%d/", verbose_name="Изображение"
            ),
        ),
    ]
